"""Add active column to User

Revision ID: 5501368392d8
Revises: 09e6a4abb03e
Create Date: 2025-09-21 11:42:22.660063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5501368392d8'
down_revision = '09e6a4abb03e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('aspects_json')
        batch_op.drop_column('pipeline_steps')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_steps', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('aspects_json', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
